### ISSUE TITLE
Add DI + Rx

### ISSUE THREAD

**Issue by MrIceman** [ercanduman/NoteTakingApp#1]
Hello, I have read abit through your Code.
I highly suggest you to use DI and unit test your domain code and your view model. Being able to write clean unit tests and therefore testable code is a required skill for intermediate developers.
Additionally to that I would also avoid using AsyncTasks and use Rx, as this is a common industry standard

best wishes and good luck

**Comment by ercanduman** [comment]
Thank you for your suggestions

Best,
